# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:            "Ove's Notes"
tagline:          'Notes about This and That and Softwares'
description:      'An absurdist. Learning Computers, One Abstraction Layer a Year.' 
url:              https://ovebepari.github.io
logo:             /favicon.ico
baseurl:          ''

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin

author:
  name: 'ovebepari'
  url: https://github.com/ovebepari
  twitter: "ovebepari"

# Post related global variables
defaultpostimage: /post_images/ove.jpg

# For a global message in the head
message: 

exclude: []
