# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:            "Ove's Notes"
tagline:          'Notes about This and That and Softwares'
description:      'An absurdist. Learning Computers, One Abstraction Layer a Year.' 
url:              https://ovebepari.github.io
baseurl:          ''

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin

author:
  name: 'ovebepari'
  url: https://github.com/ovebepari
  twitter: "ovebepari"


# For a global message in the head
message: "I plan to contribute at least one commit to CURL project this year <del>2021</del> 2022, this is a reminder!"

exclude: []
